projects:
  happoriapi:
    schemaPath: amplify/backend/api/happoriapi/build/schema.graphql
    includes:
      - site/src/graphql/**/*.js
    excludes:
      - ./site/amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ""
        docsFilePath: site/src/graphql
extensions:
  amplify:
    version: 3
