[build]
  functions = "site/functions"

[dev] 
  framework = "#custom"
  command = "yarn develop" # Command to start your dev server
  targetPort = 8008 # port the app runs on
  port = 8000 # port Netlify Dev runs on
  # functionsPort = 34568
  # publish = "site/public" # Folder with the static content for _redirect file

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200